---
title: "GadgetR: Gadget and FLR Example"
author: "Ibrahim Umar"
date: "`r Sys.Date()`"
package: gadgetr
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{GadgetR: Gadget and FLR Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
# Set simulation time parameters
firstYear <- 1978
projYear <- 2000
finalYear <- 2020

# Set up a stock (or stocks) for Gadget
## List all the unique species
#stockList <- c("had", "cod")
stockList <- c("had")

# HAD
## List all the fleets for all the species
had.fleets <- c("comm", "survey", "future")

## List all the different stock category for had
had.stocks <- c("had")

## List all the mature stock category for had
had.stocks.mature <- c("had")

## List the survey fleets for had
had.surveys <- c("survey")

## List the forecast fleets for had 
had.forecasts <- c("future")

## Set stock parameters for the OM
# m2 = NULL means we calculate m2 from gadget result, m2 = 0 means we use only residual mortality (m1)
# StockStep: in which step we should observe the stock number
had.params <- list(stockStep = 2, minage = 1, maxage = 10, minfbar = 2, maxfbar = 8,
                   startf = 0.56, endf = 0.65, areas = c(1), m1 = c(0.2), m2 = NULL)

# COD (if applicable)
#cod.fleets <- c("cod.comm", "cod.survey")
#cod.stocks <- c("cod")
#had.params <- list(stockStep = 2, minage = 1, maxage = 8, minfbar = 4, maxfbar = 8,
#                   startf = 0.56, endf = 0.65, areas = c(1), m1 = c(0.2), m2 = NULL)
#...


# Helpers for transforming the above into the new parameter format
parameterize <- function() {
  # Make the global structure
  prm <- list(firstYear = firstYear,
          projYear = projYear,
          finalYear = finalYear,
          stockList = stockList)

  # Process each stock
  for(stock in prm$stockList){
      prm[[stock]] <- list()
      prm[[stock]][["params"]] <- eval(parse(text=paste0(stock, ".params")))
      prm[[stock]][["fleets"]] <- eval(parse(text=paste0(stock, ".fleets")))
      prm[[stock]][["stocks"]] <- eval(parse(text=paste0(stock, ".stocks")))
      prm[[stock]][["stocks.mature"]] <- eval(parse(text=paste0(stock, ".stocks.mature")))
      prm[[stock]][["surveys"]] <- eval(parse(text=paste0(stock, ".surveys")))
      prm[[stock]][["forecasts"]] <- eval(parse(text=paste0(stock, ".forecasts")))
  }
  return(prm)
}


# Predict recruitment
predict_recruitment <- function(stk, model) {

	# Create the model
	newFL <- fmle(as.FLSR(stk, model=model))

	# Get the latest ssb
	ssb <- tail(ssb(stk), 1)

	# Predict
  prm <- params(newFL)

	s <- a <- prm[[1]] # Extract 'a' parameter

  if(length(prm) > 1)
	  R0 <- b <- params(newFL)[[2]] # Extract 'b' parameter

  if(length(prm) > 2)
	  v <- c <- params(newFL)[[3]] # Extract 'c' parameter

	# Use the model formula in FLCore
	rec <- eval(parse(text = as.character(model()$model[3])))

	return(list(srmodel = newFL, rec = as.numeric(rec)))
}

# Predict TAC (no assessment, using real data)
predict_TAC <- function(year, stk, idx, srmodel) {

  # Cherry-picked from: https://flr-project.org/doc/An_introduction_to_MSE_using_FLR.html
  # Year needs to be carefully checked

  getCtrl <- function(values, quantity, years, it){
      dnms <- list(iter=1:it, year=years, c("min", "val", "max"))
      arr0 <- array(NA, dimnames=dnms, dim=unlist(lapply(dnms, length)))
      arr0[,,"val"] <- unlist(values)
      arr0 <- aperm(arr0, c(2,3,1))
      ctrl <- fwdControl(data.frame(year=years, quantity=quantity, val=NA))
      ctrl@trgtArray <- arr0
      ctrl
  }

  brp <- brp(FLBRP(stk, srmodel))
  Fmsy <- c(refpts(brp)["msy","harvest"])
  msy <- c(refpts(brp)["msy","yield"])
  Bmsy <- c(refpts(brp)["msy","ssb"])
  Bpa <- 0.5 * Bmsy
  Blim <- Bpa / 1.4

  flag <- ssb(stk)[, as.character(year - 1)] < Bpa
  Ftrgt <- ifelse(flag, ssb(stk)[, as.character(year - 1)] * Fmsy / Bpa, Fmsy)

  sqy <- as.character(c((year - 3):(year-1)))
  fsq <- yearMeans(fbar(stk)[, sqy]) # Use status quo
  ctrl <- getCtrl(c(fsq, Ftrgt), "f", c(year, year + 1), 1)
  stk <- stf(stk, 2)
  gmean_rec <- c(exp(yearMeans(log(rec(stk)))))
  stk <- fwd(stk, control=ctrl, sr=list(model="mean", params = FLPar(gmean_rec,iter=1)))

  TAC <- catch(stk)[, as.character(year)]

	return(TAC)
}



runHadSingle <- function(params, modelsel) {

  library(FLCore)
  library(FLBRP)
  library(FLash)
  library(gadgetr)

	# Clean any prior gadget run
	endGadget()

	# Get the path of the example haddock data
	exPath <- loadExample()

	# Init the haddock model
	initGadget(exPath, "refinputfile")

	# Run the hindcast period
	gadgetFLR <- runUntil(params[["projYear"]] - 1, params)

  yrList <- c(params[["projYear"]]:params[["finalYear"]])

	for(year in yrList) {
		print(year)

    # Loop through unique stocks
    for(sp in params$stockList) {
      # Predict and update recruitment
		  pr <- predict_recruitment(gadgetFLR[[sp]]$stk, model = modelsel)
      rec <- round(pr$rec/10000)
		  updateRenewal(sp, year, step = 1, area = 1, age = 1,
            number = rec, mean = 16.41, sdev = 2.25 ,
		        alpha = 8.85e-6, beta = 3.0257)

      # Predict and update catch
		  tac <- predict_TAC(year, gadgetFLR[[sp]]$stk, gadgetFLR[[sp]]$idx, pr$srmodel)
      tacPortion <- c(0.232, 0.351, 0.298, 0.119)
      targetFleet <- params[[sp]][["forecasts"]]
      updateAmount(targetFleet, year, 1, 1, tacPortion[[1]] * tac)
      updateAmount(targetFleet, year, 2, 1, tacPortion[[2]] * tac)
      updateAmount(targetFleet, year, 3, 1, tacPortion[[3]] * tac)
      updateAmount(targetFleet, year, 4, 1, tacPortion[[4]] * tac)
    }

    # Forward a year
    out <- runYear()

    # Loop through unique stocks to update the FLR objects
    for(sp in params$stockList) {
      gadgetFLR[[sp]]$stk <- window(gadgetFLR[[sp]]$stk, end = year)
      gadgetFLR[[sp]]$idx <- window(gadgetFLR[[sp]]$idx, end = year)

      gadgetFLR[[sp]] <- updateFLStock(sp, out, as.character(year),
          gadgetFLR[[sp]]$stk, gadgetFLR[[sp]]$idx, params)
    }
	}

  return(gadgetFLR)

}


library(parallel)
library(FLCore)
library(ggplotFL)

chk <- Sys.getenv("_R_CHECK_LIMIT_CORES_", "")

if (nzchar(chk) && chk == "TRUE") {
    # use 2 cores in CRAN/actions
    num_workers <- 2L
} else {
    # use all cores in devtools::test()
    num_workers <- detectCores()
}

cl <- makeCluster(num_workers, type = "PSOCK")

params <- parameterize()

# Export functions and simulation parameter
clusterExport(cl, c("runHadSingle", "predict_TAC", 
                      "predict_recruitment", "params"))

# Try to run with many different recruitment models in parallel
models <- c(bevholt, ricker, cushing, geomean, segreg, shepherd, bevholtAR1,
            rickerAR1, segregAR1)
result <- parLapply(cl, models, function(x) runHadSingle(params, x))

stopCluster(cl)

# plot it
had.stk <- result[[1]]$had$stk
had.stk <- propagate(had.stk, length(models))

for(i in c(1:length(models))) {
  iter(had.stk, i) <- result[[i]]$had$stk
}
```

```{r plot, fig.height=5, fig.width=7, fig.fullwidth=TRUE, fig.cap = "Haddock model prediction using several different stock recruitment models"}

plot(had.stk)

```